language: ruby
rvm:
  - 2.4.1

deploy:
  provider: pages
  skip_cleanup: true
  on:
    branch: master


services:
  - mysql

test:
  adapter: mysql2
  database: db_test
  username: root
  encoding: utf8

development:
  adapter: mysql2
  database: db
  username: root
  encoding: utf8

before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS db_test;'
